services:
  webui:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    image: audiodit-webui:latest
    container_name: audiodit-webui
    runtime: nvidia
    user: "1000:1000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    volumes:
      - ./models:/models
      - ./outputs:/app/outputs
      - ./assets:/app/assets
      - ./samples:/app/samples
      - ./polyphone_rules.json:/app/polyphone_rules.json
      # webui开发时挂载
      - ./:/app
    ports:
      - "7860:7860"
    restart: unless-stopped
